# Generated by Django 3.0.2 on 2020-03-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is the text description of the product on the website made by himanshu.'),
            preserve_default=False,
        ),
    ]
